### ISSUE TITLE
[Question] What's AUTOSQUASH_TOKEN ?

### ISSUE THREAD

**Issue by MaicolBen** [tibdex/autosquash#19]
Do I have to name it like that when I create the token? Or should I paste the token plan in the yaml file?

**Comment by bjchambers** [comment]
Adding on to this, it would be helpful if this was mentioned in the README, as well as which permission the token needs to have.

**Comment by tibdex** [comment]
It's explained here:

https://github.com/tibdex/autosquash/blob/982dbef038e6eac178271383da91564e446efe4f/.github/workflows/autosquash.yml#L30-L36

It's a workaround until GitHub supports [triggering a new workflow from another workflow run with `GITHUB_TOKEN`]( https://github.community/t5/GitHub-Actions/Triggering-a-new-workflow-from-another-workflow/td-p/31676).

You should [create a personal token with `repo` access](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) and add it as a [repo secret](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables). The token name doesn't matter but it doesn't hurt to call it `Autosquash` so that your future self know what it's for. You can give a different name than `AUTOSQUASH_TOKEN` to the secret but then don't forget to change it too in your workflow file.
